# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo yellow

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
        @ECHO OFF
        javac NameReader.java
        java NameReader
        fc /b sortedNames.txt SortedText.txt > nul
        echo.
        if errorlevel 1 (
            echo The Sorted text in sortedNames does not match the text from our already sorted text in SortedText!
        ) else (
            echo The Sorted text in sortedNames matches the text from our already sorted text in SortedText!
        )
        echo.
        java NameReader Reverse
        fc /b sortedNames.txt SortedTextReverse.txt > nul
        echo.
        if errorlevel 1 (
            echo The Reversed Sorted text in sortedNames does not match the text from our already reverse sorted text in SortedTextReverse!
        ) else (
            echo The Reversed Sorted text in sortedNames matches the text from our already reverse sorted text in SortedTextReverse!
        )
        echo.
        PAUSE
        
        
